[project]
name = "geo-spatial-indexing"
version = "0.1.0"
description = "Expert Listing Stage Two: Geo-spatial indexing and location normalization"
readme = "README.md"
authors = [
    { name = "Emmanuel Ebenezer", email = "ekefan.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.2",
    "fastapi[standard]>=0.141.1",
    "geoalchemy2>=0.20.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
geo-spatial-indexing = "geo_spatial_indexing:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
